### ISSUE TITLE
Any Update on when the inference code will be available?

### ISSUE THREAD

**Issue by mofos** [stylus-diffusion/stylus#1]
is there any update on when the inference code will be released?

**Comment by michaelzhiluo** [comment]
Hi @mofos , we will release it by next week!

**Comment by michaelzhiluo** [comment]
Hi All (also @mofos), I would like to apologize first for delaying this open source for too long.

Have ran into some very urgent matters and deadlines that will last until end of next week; open-sourcing will most likely have to be delayed for 2 weeks.

By then, we will also have the `Composer` have support for GPT 4 which will make it easier for users. (It seems that Gemini 1.5 and GPT 4 have pretty different responses given the same prompt). We can also look to Claude too post open source.

For now the dataset, StylusDocs is released here: https://drive.google.com/file/d/1iMYQWHraC1JT78-MYOapvGNIuLoTMO-x/view?usp=sharing

The general structure of the dataset is as follows:
```
cache/
     sd_embeddings.npy -> OpenAI embeddings from processing sd_adapters.pdl
     civit_catalog.json -> All Civit AI models/checkpoints/LoRA/embeddings etc. Pulled around early April
     sd_adapters.pkl -> Proccessed adapters from Civit AI, filtered for non NSFW.
     ultra_model/ -> Folder mapping Civit AI model ID to the Gemini Ultra improved LLM description from Stylus Refiner
```

**Comment by Miracle-0718** [comment]
I have doanload the dataset,but find that the ultra_model/ file folder do not exist.

**Comment by michaelzhiluo** [comment]
@Miracle-0718 Here is an updated link: https://drive.google.com/file/d/1iMYQWHraC1JT78-MYOapvGNIuLoTMO-x/view?usp=sharing

`ultra_model/[ID]`, where  `ID` is the civit AI model id, in `https://civitai.com/models/[ID]`

**Comment by michaelzhiluo** [comment]
@mofos @Miracle-0718 We have open sourced Stylus ;)

**Comment by chrish-slingshot** [comment]
> @mofos @Miracle-0718 We have open sourced Stylus ;)

This is awesome, thank you!
